---
title: "STAT 222 EDA"
author: "Benjamin Chang"
date: "February 11, 2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
```

# For Mobility Dataset

```{r Read in Data}
setwd('C:/Users/bench/Downloads/STAT 222/Project/Data')
mobility=read.csv('2020_US_Region_Mobility_Report.csv', header = T, na.strings ="")

```

```{r Initial Cleaning}
mobility$date=as.Date(mobility$date)
```

```{r Visualization}
usMob=mobility[is.na(mobility$sub_region_1),]
caliMob=mobility[which(mobility$iso_3166_2_code=='US-CA'),]

#US

#Grocery and Pharmacy

plot(usMob$date, usMob$grocery_and_pharmacy_percent_change_from_baseline, col = 'blue', type = 'l',
main = 'US Grocery and Pharmacy Percent Change', xlab = 'Date', 
ylab = 'Percent Change')

#Recreation Percent Change

plot(usMob$date, usMob$retail_and_recreation_percent_change_from_baseline, col = 'blue', type = 'l',
main = 'US Recreation Percent Change', xlab = 'Date', 
ylab = 'Percent Change')

#Residential Percent Change

plot(usMob$date, usMob$residential_percent_change_from_baseline, col = 'blue', type = 'l',
main = 'US Residential Percent Change', xlab = 'Date', 
ylab = 'Percent Change')

#California

#Recreation Percent Change

plot(caliMob$date, caliMob$retail_and_recreation_percent_change_from_baseline, col = 'blue', type = 'l',
main = 'California Recreation Percent Change', xlab = 'Date', 
ylab = 'Percent Change')

#Grocery and Pharmacy

plot(caliMob$date, caliMob$grocery_and_pharmacy_percent_change_from_baseline, col = 'blue', type = 'l',
main = 'California Grocery and Pharmacy Percent Change', xlab = 'Date', 
ylab = 'Percent Change')

#Residential Percent Change

plot(caliMob$date, caliMob$residential_percent_change_from_baseline, col = 'blue', type = 'l',
main = 'US Residential Percent Change', xlab = 'Date', 
ylab = 'Percent Change')

```

# For Unemployment Dataset

```{r Read in Data}
unemploy=read.csv('UnemploySA.csv', header = T, na.strings ="")

```

```{r Initial Cleaning}

nameTitle=c('FIPS Code','State and area','Year','Month', 'Civilian non-institutional population','Civilian labor force','Percent of population','Employment','Percent of population','Unemployment Total','Unemployment Rate' )

names(unemploy) <- nameTitle

unemploy=unemploy[-c(seq(1,7)),]
```

```{r Visualization}
caliUnem=unemploy[which(unemploy$'State and area'=='California'),]

#for cali

plot(caliUnem$Year, caliUnem$'Unemployment Rate', col = 'blue', type = 'l',
main = 'California Unemployment Rate by Year', xlab = 'Year', 
ylab = 'Unemployment Rate (%)')

#zoomed cali

plot(caliUnem$Month[caliUnem$Year>2019], caliUnem$'Unemployment Rate'[caliUnem$Year>2019], col = 'blue', type = 'l',
main = 'California Unemployment Rate During 2020', xlab = 'Month', 
ylab = 'Unemployment Rate (%)')

```

# Covid Cases over Time

```{r Read in Data}
covid=read.csv('uscases.csv', header = T, na.strings ="")
covidstate=read.csv('usstatecases.csv', header = T, na.strings ="")

```

```{r Initial Cleaning}
covidstate$date=as.Date(covidstate$date)
covid$date=as.Date(covid$date)

calicovid=covidstate[which(covidstate$state=='California'),]

#new cases
calicovid=calicovid %>% mutate(newcases = c(0,diff(cases)))

covid=covid %>% mutate(newcases = c(0,diff(cases)))
```

```{r Visualization}
#visualizations for cali

plot(calicovid$date, calicovid$cases, col = 'blue', type = 'l',
main = 'California COVID-19 Cases over Time', xlab = 'Date', 
ylab = 'COVID-19 Cases')

plot(calicovid$date, calicovid$newcases, col = 'blue', type = 'l',
main = 'California COVID-19 New Cases over Time', xlab = 'Date', 
ylab = 'COVID-19 New Cases')

#for us

plot(covid$date, covid$cases, col = 'blue', type = 'l',
main = 'US COVID-19 Cases over Time', xlab = 'Date', 
ylab = 'COVID-19 Cases')

plot(covid$date, covid$newcases, col = 'blue', type = 'l',
main = 'US COVID-19 New Cases over Time', xlab = 'Date', 
ylab = 'COVID-19 New Cases')

```

# For Unemployment (Sex, Race) Dataset

```{r Read in Data}
unemploym=read.csv('unemploymicro.csv', header = T, na.strings ="")

```

```{r Initial Cleaning}

nameID=c('LNS14000000','LNS14000003','LNS14000006','LNS14000009', 'LNS14000025','LNS14000026','LNS14032183')
nameTitle=c('Overall','White','Black','Latino', 'Men','Women','Asian')

for (i in 1:length(nameID)){
  unemploym$Series.ID[unemploym$Series.ID==nameID[i]]=nameTitle[i]
}
```

```{r Visualization}

for (i in 1:length(nameID)){
  dfdiv=unemploym[which(unemploym$Series.ID==nameTitle[i]),]
  
  plot(dfdiv$Year, dfdiv$Value, col = 'blue', type = 'l',
  main = 'Unemployment Rate by Year', xlab = 'Year', 
  ylab = 'Unemployment Rate (%)')
}

```